model:
  name: two_view_pipeline
  extractor:
    name: extractors.raco
    weights: /home/abhiram/thesis_resources/final_model_folder/ours_correct_det_rank_cov.pth
    subpixel_sampling: true
    ranker: true
    covariance_estimator: true

benchmarks:
  hpatches:
    data:
      preprocessing:
        resize: 640
    model:
      extractor:
        max_num_keypoints: 1024
      matcher:
        name: homography_matcher
        th_positive: 3
        th_negative: 3
    eval:
      estimator: poselib
      ransac_th: -1
  megadepth1500:
    data:
      preprocessing:
        resize: 1600
    model:
      extractor:
        max_num_keypoints: 2048
      matcher:
        name: depth_matcher
        th_positive: 5
        th_negative: 5
    eval:
      estimator: poselib
      ransac_th: -1
  eth3d:
    model:
      extractor:
        max_num_keypoints: 2048