model:
  name: two_view_pipeline
  extractor:
    name: extractors.raco
    weights: /home/abhiram/thesis_resources/final_model_folder/ours_correct_det_rank_cov.pth
    subpixel_sampling: true
    ranker: true
    covariance_estimator: true

benchmarks:
  hpatches:
    data:
      preprocessing:
        resize: 640 # TODO(Abhiram): Setting it here does not work as expected
    model:
      extractor:
        max_num_keypoints: 1024
      matcher:
        name: homography_matcher
        th_positive: 3
        th_negative: 3
    eval:
      estimator: poselib
      ransac_th: -1
